/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ort.agenda.ui.components;

import com.ort.agenda.ui.Home;
import com.ort.agenda.utils.FontUtils;
import com.ort.agenda.utils.ImageUtils;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.SwingUtilities;
import javax.swing.plaf.basic.BasicButtonUI;

/**
 *
 * @author matiasc
 */
public class CustomAlertSignout extends javax.swing.JDialog {
    
    private static final Color BUTTON_CONFIRM_COLOR = new Color(29, 29, 29);
    private static final Color BUTTON_OUT_COLOR = new Color(29, 29, 29);
    private static final Color BUTTON_IN_COLOR = new Color(20, 20, 20);
    
    private static final String THIN_FONT = "Roboto-Thin";

    /**
     * Creates new form AlertSuccess
     */
    public CustomAlertSignout(java.awt.Frame parent, boolean modal, boolean isLogin) {
        super(parent, modal);
        initComponents();
        
        if(isLogin){
            jbSignout.setVisible(false);
        }
        
        setLocationRelativeTo(null);
        
        jLabel2.setFont(FontUtils.getCustomFont(THIN_FONT, 48f));
        
        jpImage.add(ImageUtils.getJLabelImage("exit.png"));
        
        JButton[] buttons = {
            jbSignout, jbExit
        };
        for (JButton jbutton : buttons) {
            jbutton.setBackground(BUTTON_CONFIRM_COLOR);
            jbutton.setUI(new BasicButtonUI());
            jbutton.addMouseListener(new MouseListener() {
                
                @Override
                public void mouseClicked(MouseEvent e) {
                }
                
                @Override
                public void mousePressed(MouseEvent e) {
                }
                
                @Override
                public void mouseReleased(MouseEvent e) {
                }
                
                @Override
                public void mouseEntered(MouseEvent e) {
                    jbutton.setBackground(BUTTON_IN_COLOR);
                }
                
                @Override
                public void mouseExited(MouseEvent e) {
                    jbutton.setBackground(BUTTON_OUT_COLOR);
                }
            });
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jpImage = new javax.swing.JPanel();
        jbSignout = new javax.swing.JButton();
        jbExit = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sign In");
        setBackground(new java.awt.Color(29, 29, 29));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(29, 29, 29));
        jPanel1.setToolTipText("Sign in");
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 300));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sign out");

        jpImage.setBackground(new java.awt.Color(29, 29, 29));

        jbSignout.setBackground(new java.awt.Color(255, 255, 255));
        jbSignout.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbSignout.setForeground(new java.awt.Color(204, 204, 204));
        jbSignout.setText("Sign out");
        jbSignout.setAlignmentX(2.0F);
        jbSignout.setBorder(null);
        jbSignout.setPreferredSize(new java.awt.Dimension(100, 25));
        jbSignout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbSignoutMouseClicked(evt);
            }
        });

        jbExit.setBackground(new java.awt.Color(255, 255, 255));
        jbExit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbExit.setForeground(new java.awt.Color(204, 204, 204));
        jbExit.setText("Exit");
        jbExit.setAlignmentX(2.0F);
        jbExit.setBorder(null);
        jbExit.setPreferredSize(new java.awt.Dimension(100, 25));
        jbExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jpImage, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbExit, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbSignout, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpImage, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbSignout, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbExit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSignoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbSignoutMouseClicked
        this.getParent().setVisible(false);
        new Home(null).setVisible(true);
    }//GEN-LAST:event_jbSignoutMouseClicked

    private void jbExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jbExitMouseClicked
    
    public void setRelativeCenterPosition() {
        this.setLocationRelativeTo(null);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomAlertSignout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomAlertSignout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomAlertSignout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomAlertSignout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CustomAlertSignout dialog = new CustomAlertSignout(new javax.swing.JFrame(), true, true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbExit;
    private javax.swing.JButton jbSignout;
    private javax.swing.JPanel jpImage;
    // End of variables declaration//GEN-END:variables
}
