/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ort.agenda.ui;

import com.ort.agenda.utils.FontUtils;
import com.ort.agenda.utils.ImageUtils;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.plaf.basic.BasicButtonUI;
import uy.edu.ort.agendaswing.dominio.Contacto;
import uy.edu.ort.agendaswing.dominio.TipoContacto;
import uy.edu.ort.agendaswing.dominio.Usuario;
import uy.edu.ort.agendaswing.logica.FachadaServicios;

/**
 *
 * @author matiasc
 */
public class Agenda extends javax.swing.JFrame {
    
    private Usuario usuario;

    /**
     * Creates new form Home
     *
     * @param usuario
     */
    public Agenda(Usuario usuario) {
        this.usuario = usuario;
        initComponents();
        
        this.setLocationRelativeTo(null);

        //JOptionPane.showMessageDialog(this, "Login incorrecto, revise usuario y passoword y reintente.", "Login incorrecto", JOptionPane.ERROR_MESSAGE);
        jPanel6.add(ImageUtils.getJLabelImage("home-4.png"));
        
        jLabel1.setFont(FontUtils.getCustomFont("Roboto-Thin", 48f));
        jLabel2.setFont(FontUtils.getCustomFont("Roboto-Thin", 18f));
        
        jLabel3.setFont(FontUtils.getCustomFont("Roboto-Regular", 12f));
        jLabel4.setFont(FontUtils.getCustomFont("Roboto-Regular", 12f));
        jLabel5.setFont(FontUtils.getCustomFont("Roboto-Regular", 12f));
        
        jButtonAdd.setBackground(new Color(29, 29, 29));
        jButtonAdd.setUI(new BasicButtonUI());
        jButtonAdd.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
            }
            
            @Override
            public void mousePressed(MouseEvent e) {
            }
            
            @Override
            public void mouseReleased(MouseEvent e) {
            }
            
            @Override
            public void mouseEntered(MouseEvent e) {
                jButtonAdd.setBackground(new Color(255, 255, 255));
            }
            
            @Override
            public void mouseExited(MouseEvent e) {
                jButtonAdd.setBackground(new Color(29, 29, 29));
            }
        });
        
        JButton[] buttons = {
            jButtonLogout, jButtonCreate, jButtonSearchContact, jButtonHome
        };
        for (JButton jbtn : buttons) {
            jbtn.setBackground(new Color(29, 29, 29));
            jbtn.setUI(new BasicButtonUI());
            jbtn.addMouseListener(new MouseListener() {
                @Override
                public void mouseClicked(MouseEvent e) {
                }
                
                @Override
                public void mousePressed(MouseEvent e) {
                }
                
                @Override
                public void mouseReleased(MouseEvent e) {
                }
                
                @Override
                public void mouseEntered(MouseEvent e) {
                    jbtn.setBackground(new Color(20, 20, 20));
                }
                
                @Override
                public void mouseExited(MouseEvent e) {
                    jbtn.setBackground(new Color(29, 29, 29));
                }
            });
        }
        
        cargarListaContactos();
        cargarComboTiposContacto();
    }
    
    private void cargarComboTiposContacto() {
        for (TipoContacto t : FachadaServicios.getInstance().getTiposContacto()) {
            jComboContactType.addItem(t);
        }
    }
    
    private void cargarListaContactos() {
        jList1.setListData(usuario.getAgenda().getContactos().toArray());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRoot = new javax.swing.JPanel();
        pnlSide = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButtonHome = new javax.swing.JButton();
        jButtonCreate = new javax.swing.JButton();
        jButtonSearchContact = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButtonLogout = new javax.swing.JButton();
        pnlCenter = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jPanel7 = new javax.swing.JPanel();
        jtfContactName = new javax.swing.JTextField();
        jtfContactPhone = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboContactType = new javax.swing.JComboBox();
        jPanel9 = new javax.swing.JPanel();
        jButtonAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1300, 750));

        pnlRoot.setLayout(new java.awt.BorderLayout());

        pnlSide.setBackground(new java.awt.Color(20, 20, 20));
        pnlSide.setPreferredSize(new java.awt.Dimension(90, 0));

        jPanel1.setBackground(new java.awt.Color(20, 20, 20));
        jPanel1.setPreferredSize(new java.awt.Dimension(80, 160));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jButtonHome.setBackground(new java.awt.Color(255, 255, 255));
        jButtonHome.setForeground(new java.awt.Color(255, 255, 255));
        jButtonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home_20px.png"))); // NOI18N
        jButtonHome.setAlignmentX(2.0F);
        jButtonHome.setPreferredSize(new java.awt.Dimension(60, 60));
        jButtonHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonHomeMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonHome, new java.awt.GridBagConstraints());

        pnlSide.add(jPanel1);

        jButtonCreate.setBackground(new java.awt.Color(29, 29, 29));
        jButtonCreate.setForeground(new java.awt.Color(20, 20, 20));
        jButtonCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/contact_20px.png"))); // NOI18N
        jButtonCreate.setAlignmentX(2.0F);
        jButtonCreate.setPreferredSize(new java.awt.Dimension(60, 60));
        jButtonCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCreateMouseClicked(evt);
            }
        });
        pnlSide.add(jButtonCreate);

        jButtonSearchContact.setBackground(new java.awt.Color(29, 29, 29));
        jButtonSearchContact.setForeground(new java.awt.Color(20, 20, 20));
        jButtonSearchContact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/find_user_male_20px.png"))); // NOI18N
        jButtonSearchContact.setPreferredSize(new java.awt.Dimension(60, 60));
        pnlSide.add(jButtonSearchContact);

        jPanel3.setBackground(new java.awt.Color(20, 20, 20));
        jPanel3.setPreferredSize(new java.awt.Dimension(80, 200));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 25));
        pnlSide.add(jPanel3);

        jButtonLogout.setBackground(new java.awt.Color(29, 29, 29));
        jButtonLogout.setForeground(new java.awt.Color(20, 20, 20));
        jButtonLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout_rounded_up_20px.png"))); // NOI18N
        jButtonLogout.setPreferredSize(new java.awt.Dimension(60, 60));
        pnlSide.add(jButtonLogout);

        pnlRoot.add(pnlSide, java.awt.BorderLayout.WEST);

        pnlCenter.setBackground(new java.awt.Color(29, 29, 29));
        pnlCenter.setPreferredSize(new java.awt.Dimension(0, 60));

        jPanel2.setBackground(new java.awt.Color(29, 29, 29));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 58)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Create Contact");
        jPanel2.add(jLabel1);

        jPanel5.setBackground(new java.awt.Color(29, 29, 29));
        jPanel5.setForeground(new java.awt.Color(29, 29, 29));
        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        jPanel6.setBackground(new java.awt.Color(29, 29, 29));
        jPanel5.add(jPanel6);

        jPanel4.setBackground(new java.awt.Color(29, 29, 29));
        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("The most awesome phone book system");
        jPanel4.add(jLabel2);

        jPanel10.setBackground(new java.awt.Color(29, 29, 29));

        jLabel9.setBackground(new java.awt.Color(30, 30, 30));
        jLabel9.setForeground(new java.awt.Color(82, 82, 82));
        jLabel9.setText("Version 1.0.0");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        jList1.setBackground(new java.awt.Color(29, 29, 29));
        jList1.setForeground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(jList1);

        jPanel7.setBackground(new java.awt.Color(29, 29, 29));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setForeground(new java.awt.Color(204, 204, 204));
        jPanel7.setToolTipText("");

        jtfContactName.setBackground(new java.awt.Color(29, 29, 29));
        jtfContactName.setForeground(new java.awt.Color(255, 255, 255));
        jtfContactName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfContactNameActionPerformed(evt);
            }
        });

        jtfContactPhone.setBackground(new java.awt.Color(29, 29, 29));
        jtfContactPhone.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Type");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Phone");

        jPanel9.setLayout(new java.awt.BorderLayout());

        jButtonAdd.setBackground(new java.awt.Color(29, 29, 29));
        jButtonAdd.setForeground(new java.awt.Color(20, 20, 20));
        jButtonAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add_50px.png"))); // NOI18N
        jButtonAdd.setPreferredSize(new java.awt.Dimension(60, 60));
        jButtonAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAddMouseClicked(evt);
            }
        });
        jPanel9.add(jButtonAdd, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(73, 73, 73)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(22, 22, 22)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfContactName)
                    .addComponent(jtfContactPhone)
                    .addComponent(jComboContactType, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboContactType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfContactName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfContactPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlCenterLayout = new javax.swing.GroupLayout(pnlCenter);
        pnlCenter.setLayout(pnlCenterLayout);
        pnlCenterLayout.setHorizontalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCenterLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCenterLayout.createSequentialGroup()
                        .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlCenterLayout.createSequentialGroup()
                                .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
                                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 874, Short.MAX_VALUE))
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlCenterLayout.setVerticalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCenterLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlCenterLayout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(pnlCenterLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pnlRoot.add(pnlCenter, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlRoot, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCreateMouseClicked

    }//GEN-LAST:event_jButtonCreateMouseClicked

    private void jtfContactNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfContactNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfContactNameActionPerformed

    private void jButtonAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddMouseClicked
        Contacto contacto = new Contacto();
        contacto.setNombre(jtfContactName.getText());
        contacto.setTelefono(jtfContactPhone.getText());
        contacto.setTipoContacto((TipoContacto) jComboContactType.getSelectedItem());
        usuario.getAgenda().agregarContacto(contacto);
        cargarListaContactos();
    }//GEN-LAST:event_jButtonAddMouseClicked

    private void jButtonHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHomeMouseClicked
        this.setVisible(false);
        new Home(usuario).setVisible(true);
    }//GEN-LAST:event_jButtonHomeMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonCreate;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonSearchContact;
    private javax.swing.JComboBox jComboContactType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtfContactName;
    private javax.swing.JTextField jtfContactPhone;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlRoot;
    private javax.swing.JPanel pnlSide;
    // End of variables declaration//GEN-END:variables
}
