/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ort.agenda.ui;

import com.ort.agenda.dominio.Contacto;
import com.ort.agenda.dominio.Usuario;
import com.ort.agenda.ui.components.CustomAlertSignout;
import com.ort.agenda.utils.FontUtils;
import com.ort.agenda.utils.ImageUtils;
import com.ort.agenda.utils.SessionUtils;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.plaf.basic.BasicButtonUI;

/**
 *
 * @author matiasc
 */
public class Search extends javax.swing.JFrame {

    private Usuario usuario;

    private static final String NOT_CONTACT_SELECTED = "Not contact selected";

    /**
     * Creates new form Home
     *
     * @param usuario
     */
    public Search(Usuario usuario) {
        this.usuario = usuario;
        initComponents();

        this.setLocationRelativeTo(null);

        jLabel1.setFont(FontUtils.getCustomFont("Roboto-Thin", 48f));
        jLabel2.setFont(FontUtils.getCustomFont("Roboto-Thin", 18f));

        jLabel3.setFont(FontUtils.getCustomFont("Roboto-Thin", 24f));
        jLabel5.setFont(FontUtils.getCustomFont("Roboto-Thin", 24f));
        jLabel6.setFont(FontUtils.getCustomFont("Roboto-Thin", 24f));

        jlNameDetail.setFont(FontUtils.getCustomFont("Roboto-Thin", 24f));
        jlPhoneDetail.setFont(FontUtils.getCustomFont("Roboto-Thin", 24f));
        jlTypeDetail.setFont(FontUtils.getCustomFont("Roboto-Thin", 24f));

        jpLogoContact.add(ImageUtils.getJLabelImage("contact-2.png"));

        jButtonSearch.setBackground(new Color(29, 29, 29));
        jButtonSearch.setUI(new BasicButtonUI());
        jButtonSearch.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
            }

            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
                jButtonSearch.setBackground(new Color(27, 27, 27));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                jButtonSearch.setBackground(new Color(29, 29, 29));
            }
        });

        JButton[] buttons = {
            jButtonLogout, jButtonCreate, jButtonSearchContact, jButtonHome
        };
        for (JButton jbtn : buttons) {
            jbtn.setBackground(new Color(29, 29, 29));
            jbtn.setUI(new BasicButtonUI());
            jbtn.addMouseListener(new MouseListener() {
                @Override
                public void mouseClicked(MouseEvent e) {
                }

                @Override
                public void mousePressed(MouseEvent e) {
                }

                @Override
                public void mouseReleased(MouseEvent e) {
                }

                @Override
                public void mouseEntered(MouseEvent e) {
                    jbtn.setBackground(new Color(20, 20, 20));
                }

                @Override
                public void mouseExited(MouseEvent e) {
                    jbtn.setBackground(new Color(29, 29, 29));
                }
            });
        }

        cargarListaContactos();

    }

    private void cargarListaContactos() {
        jList1.setListData(usuario.getAgenda().getContactos().toArray());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRoot = new javax.swing.JPanel();
        pnlSide = new javax.swing.JPanel();
        jpPrincipalButtton = new javax.swing.JPanel();
        jButtonHome = new javax.swing.JButton();
        jpSecondaryButton = new javax.swing.JPanel();
        jButtonCreate = new javax.swing.JButton();
        jButtonSearchContact = new javax.swing.JButton();
        jpLogout = new javax.swing.JPanel();
        jButtonLogout = new javax.swing.JButton();
        pnlCenter = new javax.swing.JPanel();
        jpLogoContact = new javax.swing.JPanel();
        jpTitle = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpSubtitle = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jpImageSide = new javax.swing.JPanel();
        jpDetailContact = new javax.swing.JPanel();
        jpDetail = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlNameDetail = new javax.swing.JLabel();
        jlPhoneDetail = new javax.swing.JLabel();
        jlTypeDetail = new javax.swing.JLabel();
        jpImage = new javax.swing.JPanel();
        jpVersion = new javax.swing.JPanel();
        jpSearch = new javax.swing.JPanel();
        jButtonSearch = new javax.swing.JButton();
        jtfSearch = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1300, 850));

        pnlRoot.setLayout(new java.awt.BorderLayout());

        pnlSide.setBackground(new java.awt.Color(20, 20, 20));
        pnlSide.setPreferredSize(new java.awt.Dimension(90, 0));

        jpPrincipalButtton.setBackground(new java.awt.Color(20, 20, 20));
        jpPrincipalButtton.setPreferredSize(new java.awt.Dimension(80, 160));
        jpPrincipalButtton.setLayout(new java.awt.GridBagLayout());

        jButtonHome.setBackground(new java.awt.Color(255, 255, 255));
        jButtonHome.setForeground(new java.awt.Color(255, 255, 255));
        jButtonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home_20px.png"))); // NOI18N
        jButtonHome.setAlignmentX(2.0F);
        jButtonHome.setPreferredSize(new java.awt.Dimension(60, 60));
        jButtonHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonHomeMouseClicked(evt);
            }
        });
        jpPrincipalButtton.add(jButtonHome, new java.awt.GridBagConstraints());

        pnlSide.add(jpPrincipalButtton);

        jpSecondaryButton.setBackground(new java.awt.Color(20, 20, 20));
        jpSecondaryButton.setPreferredSize(new java.awt.Dimension(80, 200));
        jpSecondaryButton.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 25));

        jButtonCreate.setBackground(new java.awt.Color(29, 29, 29));
        jButtonCreate.setForeground(new java.awt.Color(20, 20, 20));
        jButtonCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/contact_20px.png"))); // NOI18N
        jButtonCreate.setAlignmentX(2.0F);
        jButtonCreate.setPreferredSize(new java.awt.Dimension(60, 60));
        jButtonCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCreateMouseClicked(evt);
            }
        });
        jpSecondaryButton.add(jButtonCreate);

        jButtonSearchContact.setBackground(new java.awt.Color(29, 29, 29));
        jButtonSearchContact.setForeground(new java.awt.Color(20, 20, 20));
        jButtonSearchContact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/find_user_male_20px.png"))); // NOI18N
        jButtonSearchContact.setPreferredSize(new java.awt.Dimension(60, 60));
        jButtonSearchContact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSearchContactMouseClicked(evt);
            }
        });
        jpSecondaryButton.add(jButtonSearchContact);

        pnlSide.add(jpSecondaryButton);

        jpLogout.setBackground(new java.awt.Color(20, 20, 20));

        jButtonLogout.setBackground(new java.awt.Color(29, 29, 29));
        jButtonLogout.setForeground(new java.awt.Color(20, 20, 20));
        jButtonLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout_rounded_up_20px.png"))); // NOI18N
        jButtonLogout.setPreferredSize(new java.awt.Dimension(60, 60));
        jButtonLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLogoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpLogoutLayout = new javax.swing.GroupLayout(jpLogout);
        jpLogout.setLayout(jpLogoutLayout);
        jpLogoutLayout.setHorizontalGroup(
            jpLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jpLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpLogoutLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jpLogoutLayout.setVerticalGroup(
            jpLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 123, Short.MAX_VALUE)
            .addGroup(jpLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpLogoutLayout.createSequentialGroup()
                    .addGap(0, 31, Short.MAX_VALUE)
                    .addComponent(jButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 32, Short.MAX_VALUE)))
        );

        pnlSide.add(jpLogout);

        pnlRoot.add(pnlSide, java.awt.BorderLayout.WEST);

        pnlCenter.setBackground(new java.awt.Color(29, 29, 29));
        pnlCenter.setPreferredSize(new java.awt.Dimension(0, 60));

        jpLogoContact.setBackground(new java.awt.Color(29, 29, 29));
        jpLogoContact.setLayout(new java.awt.BorderLayout());

        jpTitle.setBackground(new java.awt.Color(29, 29, 29));
        jpTitle.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 58)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Search Contact");
        jpTitle.add(jLabel1);

        jpSubtitle.setBackground(new java.awt.Color(29, 29, 29));
        jpSubtitle.setLayout(new java.awt.GridLayout(1, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jpSubtitle.add(jLabel2);

        jpImageSide.setBackground(new java.awt.Color(29, 29, 29));
        jpImageSide.setForeground(new java.awt.Color(29, 29, 29));
        jpImageSide.setLayout(new java.awt.GridLayout(1, 0));

        jpDetailContact.setBackground(new java.awt.Color(29, 29, 29));

        jpDetail.setBackground(new java.awt.Color(29, 29, 29));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Type");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Phone");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name");

        jlNameDetail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlNameDetail.setForeground(new java.awt.Color(255, 255, 255));
        jlNameDetail.setText("Not contact selected");

        jlPhoneDetail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlPhoneDetail.setForeground(new java.awt.Color(255, 255, 255));
        jlPhoneDetail.setText("Not contact selected");

        jlTypeDetail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlTypeDetail.setForeground(new java.awt.Color(255, 255, 255));
        jlTypeDetail.setText("Not contact selected");

        javax.swing.GroupLayout jpDetailLayout = new javax.swing.GroupLayout(jpDetail);
        jpDetail.setLayout(jpDetailLayout);
        jpDetailLayout.setHorizontalGroup(
            jpDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDetailLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(jpDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3))
                .addGap(38, 38, 38)
                .addGroup(jpDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlNameDetail)
                    .addComponent(jlTypeDetail)
                    .addComponent(jlPhoneDetail))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpDetailLayout.setVerticalGroup(
            jpDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDetailLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jpDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jlNameDetail))
                .addGap(62, 62, 62)
                .addGroup(jpDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jlPhoneDetail))
                .addGap(66, 66, 66)
                .addGroup(jpDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jlTypeDetail))
                .addContainerGap(149, Short.MAX_VALUE))
        );

        jpImage.setBackground(new java.awt.Color(29, 29, 29));

        javax.swing.GroupLayout jpImageLayout = new javax.swing.GroupLayout(jpImage);
        jpImage.setLayout(jpImageLayout);
        jpImageLayout.setHorizontalGroup(
            jpImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 844, Short.MAX_VALUE)
        );
        jpImageLayout.setVerticalGroup(
            jpImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 301, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpDetailContactLayout = new javax.swing.GroupLayout(jpDetailContact);
        jpDetailContact.setLayout(jpDetailContactLayout);
        jpDetailContactLayout.setHorizontalGroup(
            jpDetailContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDetailContactLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDetailContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpDetailContactLayout.setVerticalGroup(
            jpDetailContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDetailContactLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jpDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpImageSide.add(jpDetailContact);

        jpVersion.setBackground(new java.awt.Color(29, 29, 29));

        javax.swing.GroupLayout jpVersionLayout = new javax.swing.GroupLayout(jpVersion);
        jpVersion.setLayout(jpVersionLayout);
        jpVersionLayout.setHorizontalGroup(
            jpVersionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpVersionLayout.setVerticalGroup(
            jpVersionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        jpSearch.setBackground(new java.awt.Color(29, 29, 29));
        jpSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpSearch.setForeground(new java.awt.Color(204, 204, 204));
        jpSearch.setToolTipText("");

        jButtonSearch.setBackground(new java.awt.Color(29, 29, 29));
        jButtonSearch.setForeground(new java.awt.Color(20, 20, 20));
        jButtonSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search_100px.png"))); // NOI18N
        jButtonSearch.setPreferredSize(new java.awt.Dimension(60, 60));
        jButtonSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSearchMouseClicked(evt);
            }
        });

        jtfSearch.setBackground(new java.awt.Color(29, 29, 29));
        jtfSearch.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Search criteria");

        javax.swing.GroupLayout jpSearchLayout = new javax.swing.GroupLayout(jpSearch);
        jpSearch.setLayout(jpSearchLayout);
        jpSearchLayout.setHorizontalGroup(
            jpSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpSearchLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jtfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpSearchLayout.setVerticalGroup(
            jpSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSearchLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jpSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jButtonSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jList1.setBackground(new java.awt.Color(29, 29, 29));
        jList1.setForeground(new java.awt.Color(204, 204, 204));
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout pnlCenterLayout = new javax.swing.GroupLayout(pnlCenter);
        pnlCenter.setLayout(pnlCenterLayout);
        pnlCenterLayout.setHorizontalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCenterLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCenterLayout.createSequentialGroup()
                        .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpSubtitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlCenterLayout.createSequentialGroup()
                                .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane1)
                                        .addComponent(jpSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(pnlCenterLayout.createSequentialGroup()
                                        .addComponent(jpLogoContact, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jpTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpImageSide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jpVersion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlCenterLayout.setVerticalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCenterLayout.createSequentialGroup()
                .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCenterLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jpImageSide, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlCenterLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jpLogoContact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpSubtitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addComponent(jpVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pnlRoot.add(pnlCenter, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlRoot, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCreateMouseClicked
        this.setVisible(false);
        new Agenda(usuario).setVisible(true);
    }//GEN-LAST:event_jButtonCreateMouseClicked

    private void jButtonSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSearchMouseClicked
        ArrayList<Contacto> contactos = usuario.getAgenda().buscarContactos(jtfSearch.getText());
        jList1.setListData(contactos.toArray());
        jList1.updateUI();

        cleanContactDetail();
    }//GEN-LAST:event_jButtonSearchMouseClicked

    private void jButtonHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHomeMouseClicked
        this.setVisible(false);
        new Home(usuario).setVisible(true);
    }//GEN-LAST:event_jButtonHomeMouseClicked

    private void jButtonLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLogoutMouseClicked
        new CustomAlertSignout(this, true, !SessionUtils.checkLogin(usuario)).setVisible(true);
    }//GEN-LAST:event_jButtonLogoutMouseClicked

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        updateContactDetail();
    }//GEN-LAST:event_jList1MouseClicked

    public void updateContactDetail() {
        Contacto contacto = (Contacto) jList1.getSelectedValue();
        jlNameDetail.setText(contacto.getNombre());
        jlPhoneDetail.setText(contacto.getTelefono());
        jlTypeDetail.setText(contacto.getTipoContacto().getNombre());
    }

    private void jButtonSearchContactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSearchContactMouseClicked

    }//GEN-LAST:event_jButtonSearchContactMouseClicked

    private void cleanContactDetail() {
        jlNameDetail.setText(NOT_CONTACT_SELECTED);
        jlPhoneDetail.setText(NOT_CONTACT_SELECTED);
        jlTypeDetail.setText(NOT_CONTACT_SELECTED);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCreate;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonSearchContact;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlNameDetail;
    private javax.swing.JLabel jlPhoneDetail;
    private javax.swing.JLabel jlTypeDetail;
    private javax.swing.JPanel jpDetail;
    private javax.swing.JPanel jpDetailContact;
    private javax.swing.JPanel jpImage;
    private javax.swing.JPanel jpImageSide;
    private javax.swing.JPanel jpLogoContact;
    private javax.swing.JPanel jpLogout;
    private javax.swing.JPanel jpPrincipalButtton;
    private javax.swing.JPanel jpSearch;
    private javax.swing.JPanel jpSecondaryButton;
    private javax.swing.JPanel jpSubtitle;
    private javax.swing.JPanel jpTitle;
    private javax.swing.JPanel jpVersion;
    private javax.swing.JTextField jtfSearch;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlRoot;
    private javax.swing.JPanel pnlSide;
    // End of variables declaration//GEN-END:variables
}
